#!/bin/sh

opts=""

while true; do

    if [ -f .prettieropts ]; then
        opts=$(cat .prettieropts |  tr '\n' ' ')
        break
    fi

    if [ "$(pwd)" = "/" ]; then
        break
    fi

    cd ..

done

exec prettier $opts "$@"